
# telegram bot token
TELEGRAM_BOT_TOKEN=""
# telegram chat id
TELEGRAM_CHAT_ID=""
# telegram message thread id
TELEGRAM_MESSAGE_THREAD_ID=""

# proxy address
PROXY_URL=""

# scraper time duration (min)
SCRAPER_TIME_DURATION=1

# feishu bot hook
FEISHU_BOT_HOOK_TOKEN=""